### ISSUE TITLE
[BUG] AttributeError: 'PageNumberPaginationExtra' object has no attribute 'pass_parameter'

### ISSUE THREAD

**Issue by facundopadilla** [eadwinCode/django-ninja-extra#10]
Hello!, I just upgraded to the latest version but it's giving me problems with pagination

```sh
'PageNumberPaginationExtra' object has no attribute 'pass_parameter'
Traceback (most recent call last):
  File "/home/facundo/PycharmProjects/senyp/env_clinica/lib/python3.8/site-packages/ninja_extra/operation.py", line 158, in run
    result = self.view_func(context=ctx, **values)
  File "/home/facundo/PycharmProjects/senyp/env_clinica/lib/python3.8/site-packages/ninja_extra/controllers/route/route_functions.py", line 69, in as_view
    result = self.route.view_func(
  File "/home/facundo/PycharmProjects/senyp/env_clinica/lib/python3.8/site-packages/ninja_extra/pagination.py", line 224, in as_view
    if self.paginator.pass_parameter:
AttributeError: 'PageNumberPaginationExtra' object has no attribute 'pass_parameter'
Internal Server Error: /api/v1/medics
[19/Feb/2022 21:37:57] "GET /api/v1/medics?page=1&page_size=100 HTTP/1.1" 500 660
```

**I made a small modification in the line where the error is occurring and it was solved.**

```python
# ninja_extra/pagination.py
def get_view_function(self) -> Callable:
    def as_view(controller: "ControllerBase", *args: Any, **kw: Any) -> Any:
        func_kwargs = dict(**kw)
        pagination_params = func_kwargs.pop(self.paginator_kwargs_name)
        if hasattr(self.paginator, "pass_parameter"):   # Old: if self.paginator.pass_parameter
            func_kwargs[self.paginator.pass_parameter] = pagination_params
```

**Comment by facundopadilla** [comment]
My code:

```python
@route.get(path="", description="Get all localities or filter", response=PaginatedResponseSchema[LocalitySchema], auth=auth_api_key)
    @paginate
    def get_all_or_filter(self, request: HttpRequest):
        query_params = get_query_params(request=request, as_dict=True)
        if query_params:
            return LocalityService.filter(**query_params)
        return LocalityService.get_all()
```

**Comment by facundopadilla** [comment]
Fixed, update the django ninja library
