### ISSUE TITLE
Type hinting generic list not supported (PEP 585)

### ISSUE THREAD

**Issue by M3te0r** [eadwinCode/django-ninja-extra#11]
Hi, it seems that django-ninja-extra does not support generic type hinting on collections
Python 3.10
django-ninja : 0.17.0
django-ninja-extra : 0.14.4

NOK :
```
class UserOut(Schema):
    email: str
    last_login: datetime

@api_controller("/users_extra")
class UsersAPIController(ControllerBase):
    @http_get("/", response=list[UserOut])  # <-------- list instead of List
    def get_users(self, request: HttpRequest):
        return User.objects.all()

```
Traceback asociated : 
```
Traceback (most recent call last):
  File "/home/mete0r/.pyenv/versions/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/mete0r/.pyenv/versions/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mete0r/PycharmProjects/bepatient-server/.venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/mete0r/PycharmProjects/bepatient-server/.venv/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 134, in inner_run
    self.check(display_num_errors=True)
  File "/home/mete0r/PycharmProjects/bepatient-server/.venv/lib/python3.10/site-packages/django/core/management/base.py", line 487, in check
    all_issues = checks.run_checks(
  File "/home/mete0r/PycharmProjects/bepatient-server/.venv/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/mete0r/PycharmProjects/bepatient-server/.venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/home/mete0r/PycharmProjects/bepatient-server/.venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/home/mete0r/PycharmProjects/bepatient-server/.venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 480, in check
    for pattern in self.url_patterns:
  File "/home/mete0r/PycharmProjects/bepatient-server/.venv/lib/python3.10/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/mete0r/PycharmProjects/bepatient-server/.venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 696, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/mete0r/PycharmProjects/bepatient-server/.venv/lib/python3.10/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/mete0r/PycharmProjects/bepatient-server/.venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 689, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/mete0r/.pyenv/versions/3.10.0/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mete0r/PycharmProjects/bepatient-server/config/urls.py", line 13, in <module>
    path("api/", include("nova.api.urls")),
  File "/home/mete0r/PycharmProjects/bepatient-server/.venv/lib/python3.10/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/mete0r/.pyenv/versions/3.10.0/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mete0r/PycharmProjects/bepatient-server/nova/api/urls.py", line 3, in <module>
    from nova.api.endpoints import api
  File "/home/mete0r/PycharmProjects/bepatient-server/nova/api/endpoints.py", line 10, in <module>
    from nova.dynamic_forms.api.api import FormAPIController
  File "/home/mete0r/PycharmProjects/bepatient-server/nova/dynamic_forms/api/api.py", line 221, in <module>
    class UsersAPIController(ControllerBase):
  File "/home/mete0r/PycharmProjects/bepatient-server/nova/dynamic_forms/api/api.py", line 222, in UsersAPIController
    @http_get("/", response=list[UserOut])
  File "/home/mete0r/PycharmProjects/bepatient-server/.venv/lib/python3.10/site-packages/ninja_extra/controllers/route/__init__.py", line 64, in http_get
    return Route(
  File "/home/mete0r/PycharmProjects/bepatient-server/.venv/lib/python3.10/site-packages/ninja_extra/controllers/route/__init__.py", line 456, in __init__
    inspect.isclass(response) and issubclass(response, ControllerResponse)
  File "/home/mete0r/.pyenv/versions/3.10.0/lib/python3.10/abc.py", line 123, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
TypeError: issubclass() arg 1 must be a class

```

OK : 
```
from typing import List

class UserOut(Schema):
    email: str
    last_login: datetime

@api_controller("/users_extra")
class UsersAPIController(ControllerBase):
    @http_get("/", response=List[UserOut])  # <-------- List instead of list
    def get_users(self, request: HttpRequest):
        return User.objects.all()
```

**Comment by eadwinCode** [comment]
@M3te0r, this is not yet supported in django-ninja library

**Comment by eadwinCode** [comment]
@M3te0r I think I understand what going on now. I will look into it

**Comment by M3te0r** [comment]
Thanks @eadwinCode for fixing this !
