### ISSUE TITLE
Failed to load API definition - /api/docs 

### ISSUE THREAD

**Issue by jankrnavek** [eadwinCode/django-ninja-extra#66]
On /api/docs endpoint i get this html error.

Python version: 3.11.3
Django version: 4.2.2
Django-Ninja version: 0.22.1
Django-Ninja-Extra 0.18.9

With previous version  everthing works fine. 
(Django-Ninja version: 0.21.x, Django-Ninja-Extra 0.18.8)

```
Failed to load API definition.
Errors
Fetch error
Internal Server Error /api/openapi.json
```

**Comment by jankrnavek** [comment]
The above problem is fixed, please update your package to support the latest django-ninja.
Thnak you.

**Comment by jankrnavek** [comment]
Hello @eadwinCode ,
one more note  your django-ninja-jwt = "5.25" doens't work as well,   "5.2.2" is OK

**Comment by eadwinCode** [comment]
@jankrnavek can you be more specific to what you mean by `doesn't work`?

**Comment by jankrnavek** [comment]
Poetry update output:


```
(mabb-py3.11) PS C:\git\mabb> poetry update
Updating dependencies
Resolving dependencies...

Package operations: 0 installs, 1 update, 3 removals

  • Removing dnspython (2.3.0)
  • Removing email-validator (2.0.0.post2)
  • Removing ninja-schema (0.13.0)
  • Updating django-ninja-jwt (5.2.2 -> 5.2.5)

Writing lock file
```


Errors in log after restarting Gunicorn:

```
Traceback (most recent call last):
  File "/home/webhosting/mabb/env/lib/python3.11/site-packages/django/template/base.py", line 890, in _resolve_lookup
    current = getattr(current, bit)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NinjaJWTUserDefinedSettingsMapper' object has no attribute 'JSON_ENCODER'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/webhosting/mabb/env/lib/python3.11/site-packages/django/template/base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'JSON_ENCODER'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/webhosting/mabb/env/lib/python3.11/site-packages/django/template/base.py", line 903, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [JSON_ENCODER] in <ninja_jwt.settings.NinjaJWTUserDefinedSettingsMapper object at 0x7f3f39f94ad0>
Exception while resolving variable 'JSON_ENCODER' in template 'unknown'.
Traceback (most recent call last):
  File "/home/webhosting/mabb/env/lib/python3.11/site-packages/ninja/schema.py", line 54, in __getitem__
    item = getattr(self._obj, key)
           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NinjaJWTUserDefinedSettingsMapper' object has no attribute 'JSON_ENCODER'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/webhosting/mabb/env/lib/python3.11/site-packages/django/template/base.py", line 880, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
TypeError: 'NinjaJWTUserDefinedSettingsMapper' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/webhosting/mabb/env/lib/python3.11/site-packages/django/template/base.py", line 890, in _resolve_lookup
    current = getattr(current, bit)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NinjaJWTUserDefinedSettingsMapper' object has no attribute 'JSON_ENCODER'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/webhosting/mabb/env/lib/python3.11/site-packages/django/template/base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'JSON_ENCODER'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/webhosting/mabb/env/lib/python3.11/site-packages/django/template/base.py", line 903, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [JSON_ENCODER] in <ninja_jwt.settings.NinjaJWTUserDefinedSettingsMapper object at 0x7f3f39f950d0>
Exception while resolving variable 'JSON_ENCODER' in template 'unknown'.
Traceback (most recent call last):
  File "/home/webhosting/mabb/env/lib/python3.11/site-packages/ninja/schema.py", line 54, in __getitem__
    item = getattr(self._obj, key)
           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NinjaJWTUserDefinedSettingsMapper' object has no attribute 'JSON_ENCODER'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/webhosting/mabb/env/lib/python3.11/site-packages/django/template/base.py", line 880, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
TypeError: 'NinjaJWTUserDefinedSettingsMapper' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/webhosting/mabb/env/lib/python3.11/site-packages/django/template/base.py", line 890, in _resolve_lookup
    current = getattr(current, bit)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NinjaJWTUserDefinedSettingsMapper' object has no attribute 'JSON_ENCODER'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/webhosting/mabb/env/lib/python3.11/site-packages/django/template/base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'JSON_ENCODER'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/webhosting/mabb/env/lib/python3.11/site-packages/django/template/base.py", line 903, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [JSON_ENCODER] in <ninja_jwt.settings.NinjaJWTUserDefinedSettingsMapper object at 0x7f3f39f950d0>
Exception while resolving variable 'JSON_ENCODER' in template 'unknown'.
Traceback (most recent call last):
  File "/home/webhosting/mabb/env/lib/python3.11/site-packages/ninja/schema.py", line 54, in __getitem__
    item = getattr(self._obj, key)
           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NinjaJWTUserDefinedSettingsMapper' object has no attribute 'JSON_ENCODER'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/webhosting/mabb/env/lib/python3.11/site-packages/django/template/base.py", line 880, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
TypeError: 'NinjaJWTUserDefinedSettingsMapper' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/webhosting/mabb/env/lib/python3.11/site-packages/django/template/base.py", line 890, in _resolve_lookup
    current = getattr(current, bit)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NinjaJWTUserDefinedSettingsMapper' object has no attribute 'JSON_ENCODER'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/webhosting/mabb/env/lib/python3.11/site-packages/django/template/base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'JSON_ENCODER'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/webhosting/mabb/env/lib/python3.11/site-packages/django/template/base.py", line 903, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [JSON_ENCODER] in <ninja_jwt.settings.NinjaJWTUserDefinedSettingsMapper object at 0x7f3f39f90250>
Exception while resolving variable 'JSON_ENCODER' in template 'unknown'.
Traceback (most recent call last):
  File "/home/webhosting/mabb/env/lib/python3.11/site-packages/ninja/schema.py", line 54, in __getitem__
    item = getattr(self._obj, key)
           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NinjaJWTUserDefinedSettingsMapper' object has no attribute 'JSON_ENCODER'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/webhosting/mabb/env/lib/python3.11/site-packages/django/template/base.py", line 880, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
TypeError: 'NinjaJWTUserDefinedSettingsMapper' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/webhosting/mabb/env/lib/python3.11/site-packages/django/template/base.py", line 890, in _resolve_lookup
    current = getattr(current, bit)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NinjaJWTUserDefinedSettingsMapper' object has no attribute 'JSON_ENCODER'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/webhosting/mabb/env/lib/python3.11/site-packages/django/template/base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'JSON_ENCODER'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/webhosting/mabb/env/lib/python3.11/site-packages/django/template/base.py", line 903, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [JSON_ENCODER] in <ninja_jwt.settings.NinjaJWTUserDefinedSettingsMapper object at 0x7f3f39f90250>
Exception while resolving variable 'JSON_ENCODER' in template 'unknown'.
Traceback (most recent call last):
  File "/home/webhosting/mabb/env/lib/python3.11/site-packages/ninja/schema.py", line 54, in __getitem__
    item = getattr(self._obj, key)
           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NinjaJWTUserDefinedSettingsMapper' object has no attribute 'JSON_ENCODER'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/webhosting/mabb/env/lib/python3.11/site-packages/django/template/base.py", line 880, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
TypeError: 'NinjaJWTUserDefinedSettingsMapper' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/webhosting/mabb/env/lib/python3.11/site-packages/django/template/base.py", line 890, in _resolve_lookup
    current = getattr(current, bit)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NinjaJWTUserDefinedSettingsMapper' object has no attribute 'JSON_ENCODER'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/webhosting/mabb/env/lib/python3.11/site-packages/django/template/base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'JSON_ENCODER'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/webhosting/mabb/env/lib/python3.11/site-packages/django/template/base.py", line 903, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [JSON_ENCODER] in <ninja_jwt.settings.NinjaJWTUserDefinedSettingsMapper object at 0x7f3f39f90250>
Exception while resolving variable 'JSON_ENCODER' in template 'unknown'.
Traceback (most recent call last):
  File "/home/webhosting/mabb/env/lib/python3.11/site-packages/ninja/schema.py", line 54, in __getitem__
    item = getattr(self._obj, key)
           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NinjaJWTUserDefinedSettingsMapper' object has no attribute 'JSON_ENCODER'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/webhosting/mabb/env/lib/python3.11/site-packages/django/template/base.py", line 880, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
TypeError: 'NinjaJWTUserDefinedSettingsMapper' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/webhosting/mabb/env/lib/python3.11/site-packages/django/template/base.py", line 890, in _resolve_lookup
    current = getattr(current, bit)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NinjaJWTUserDefinedSettingsMapper' object has no attribute 'JSON_ENCODER'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/webhosting/mabb/env/lib/python3.11/site-packages/django/template/base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'JSON_ENCODER'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/webhosting/mabb/env/lib/python3.11/site-packages/django/template/base.py", line 903, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [JSON_ENCODER] in <ninja_jwt.settings.NinjaJWTUserDefinedSettingsMapper object at 0x7f3f39f90250>

```

**Comment by eadwinCode** [comment]
I will look into this... Can you also share your settings for `NINJA_JWT` ?

**Comment by eadwinCode** [comment]
@jankrnavek Whats your pydantic version?

**Comment by jankrnavek** [comment]
C:\git\mabb> poetry show pydantic
```
 name         : pydantic                                                        
 version      : 1.10.9
 description  : Data validation and settings management using python type hints

dependencies
 - email-validator >=1.0.3
 - typing-extensions >=4.2.0

required by
 - django-ninja >=1.6,<2.0.0
 - ninja-schema *
```

**Comment by eadwinCode** [comment]
@jankrnavek I have tried to reproduce this error but its seems like its something specific to your project. Also I am a bit confused as to why a template VariableDoesNotExist exception is related to ninja_jwt settings. 
`NinjaJWTUserDefinedSettingsMapper` is used in loading ninja_jwt settings with pydantic yet I don't see any errors from pydantic.

**Comment by eadwinCode** [comment]
Can you check in your project to see if your are using `USER_SETTINGS` from `ninja_jwt` anywhere? I am guessing your project is interacting with ninja_jwt `USER_SETTINGS` variable which is a `NinjaJWTUserDefinedSettingsMapper` object

**Comment by eadwinCode** [comment]
No thats not the problem.
