### ISSUE TITLE
ROUTE_CONTEXT_VAR error when trying to use throttle.

### ISSUE THREAD

**Issue by deasek** [eadwinCode/django-ninja-extra#95]
I am trying to use simple throttling in my router function:

```python
from django.db.models import Q
from ninja import Router

from api.errors import ObjectNotFoundError
from api.schemas.entity import EntitySchema
from core.models import Entity
from ninja_extra import throttle

router = Router()


@router.get("/{identifier}", response=EntitySchema, tags=["Entity"])
@throttle
def get_entity_by_id_or_krs(request, identifier: str):
    try:
        return Entity.objects.get(Q(krs=identifier) | Q(id=identifier))
    except Entity.DoesNotExist:
        raise ObjectNotFoundError
```

but I am getting such an Exception:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/ninja/operation.py", line 108, in run
    result = self.view_func(request, **values)
  File "/usr/local/lib/python3.10/dist-packages/ninja_extra/throttling/decorator.py", line 90, in as_view
    ctx = cast(Optional[RouteContext], service_resolver(RouteContext))
  File "/usr/local/lib/python3.10/dist-packages/ninja_extra/dependency_resolver.py", line 38, in service_resolver
    return injector.get(interfaces[0])
  File "/usr/local/lib/python3.10/dist-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/injector/__init__.py", line 975, in get
    result = provider_instance.get(self)
  File "/usr/local/lib/python3.10/dist-packages/injector/__init__.py", line 302, in get
    return injector.call_with_injection(self._callable)
  File "/usr/local/lib/python3.10/dist-packages/injector/__init__.py", line 1040, in call_with_injection
    return callable(*full_args, **dependencies)
  File "/usr/local/lib/python3.10/dist-packages/ninja_extra/modules.py", line 31, in <lambda>
    binder.bind(RouteContext, to=lambda: self.get_route_context())  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/ninja_extra/modules.py", line 27, in get_route_context
    return ROUTE_CONTEXT_VAR.get()
LookupError: <ContextVar name='ROUTE_CONTEXT_VAR' at 0xffffb6595990>
```

My `settings.py` setting:
```python
NINJA_EXTRA = {
    "THROTTLE_CLASSES": [
        "ninja_extra.throttling.AnonRateThrottle",
        "ninja_extra.throttling.UserRateThrottle",
    ],
    "THROTTLE_RATES": {
        "user": "1000/day",
        "anon": "5/day",
    },
    "NUM_PROXIES": None,
}
```

I am using `django-ninja==1.0.1` and `django-ninja-extra==0.20.0`

**Comment by eadwinCode** [comment]
Ninja Extra features does not work with Ninja API routers. For your example you can use the router that comes from ninja_extra as show below:

```python
from django.db.models import Q

from api.errors import ObjectNotFoundError
from api.schemas.entity import EntitySchema
from core.models import Entity
from ninja_extra import throttle, Router

router = Router()


@router.get("/{identifier}", response=EntitySchema, tags=["Entity"])
@throttle
def get_entity_by_id_or_krs(request, identifier: str):
    try:
        return Entity.objects.get(Q(krs=identifier) | Q(id=identifier))
    except Entity.DoesNotExist:
        raise ObjectNotFoundError
```
