### ISSUE TITLE
LimitOffsetPagination does not work "Input should be a valid list"

### ISSUE THREAD

**Issue by Bouni** [eadwinCode/django-ninja-extra#96]
Hi, 

I tried pagination using `PageNumberPaginationExtra` which works as expected, but I want to use `LimitOffsetPagination` now instead which does not work unfortunately.

```python
@api_controller("machines/")
class MachineController(ControllerBase):

  @route.get("/list/{department}", response={200: list[MachineSchema]})
  @paginate
  def get_machine_list(self, department: str):
    machines = Machine.objects.filter(type__department__name=department).all()
    return machines
```

If I remove `@paginate` everything works.
I guess it has somethig to do with the query parameter `department` but I'm not sure.

Ideas how to get this working?

**Edit:**

This is the error message:

```
pydantic_core._pydantic_core.ValidationError: 1 validation error for NinjaResponseSchema
response
  Input should be a valid list [type=list_type, input_value={'items': <QuerySet [<Mac...Nr.113>]>, 'count': 105}, input_type=dict]
```

**Comment by eadwinCode** [comment]
You need to use `NinjaPaginationResponseSchema` in the route.get response parameter, see example below:
```python
from ninja_extra.schemas import NinjaPaginationResponseSchema

@api_controller("machines/")
class MachineController(ControllerBase):

  @route.get("/list/{department}", response={200: NinjaPaginationResponseSchema[MachineSchema]})
  @paginate
  def get_machine_list(self, department: str):
    machines = Machine.objects.filter(type__department__name=department).all()
    return machines
```

**Comment by Bouni** [comment]
Works like a charme 🥳 

But the docs need a small change then: https://eadwincode.github.io/django-ninja-extra/tutorial/pagination/

```python
    @route.get('/limit', response=List[UserSchema])
    @paginate
    def get_users_with_limit(self):
        # this will use default paginator class - ninja_extra.pagination.LimitOffsetPagination
        return user_model.objects.all()
```

should be

```python
    @route.get('/limit', response=NinjaPaginationResponseSchema[UserSchema])
    @paginate
    def get_users_with_limit(self):
        # this will use default paginator class - ninja_extra.pagination.LimitOffsetPagination
        return user_model.objects.all()
```

right?

**Comment by eadwinCode** [comment]
@Bouni Its actually on the docs. I guess I have to make it obvious with a heading.

Also, the second code snippet is the way it should be

**Comment by eadwinCode** [comment]
@Bouni fixed https://eadwincode.github.io/django-ninja-extra/tutorial/pagination/#using-ninja-limitoffsetpagination

**Comment by Elixir-MeetThoriya** [comment]
Hello,
i use PageNumberPaginationExtra pagination 
NINJA_EXTRA = {
    'PAGINATION_CLASS': 'ninja_extra.pagination.PageNumberPaginationExtra',
    'PAGINATION_PER_PAGE': 2,
    'ORDERING_CLASS': "ninja_extra.ordering.Ordering",
}

```
@http_get(
        path="",
        response={
            HTTPStatus.INTERNAL_SERVER_ERROR: ErrorSchema,
            HTTPStatus.OK: PaginatedResponseSchema[UserSchema],
        },
        summary="User List",
        description="This endpoint retrieves a list of users.",
        url_name="user_list"
    )
    @paginate()  # use default pagination (which define in setting.py)
    @ordering(Ordering, ordering_fields=['username'])
    @searching(Searching, search_fields=['username', 'first_name'])
    def list(self):
    .....
    ....
```
if i return ErrorSchema Response ,
it throws below error:
```
[34743 135260654274112 23/Sep/2024 10:23:50] ERROR [django:116] 4 validation errors for NinjaResponseSchema
response.results.0.id
  Field required [type=missing, input_value=<DjangoGetter: <HTTPStatu...RNAL_SERVER_ERROR: 500>>, input_type=DjangoGetter]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
response.results.0.username
  Field required [type=missing, input_value=<DjangoGetter: <HTTPStatu...RNAL_SERVER_ERROR: 500>>, input_type=DjangoGetter]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
response.results.1.id
  Field required [type=missing, input_value=<DjangoGetter: ErrorSchem...try later.', code=None)>, input_type=DjangoGetter]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
response.results.1.username
  Field required [type=missing, input_value=<DjangoGetter: ErrorSchem...try later.', code=None)>, input_type=DjangoGetter]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
Traceback (most recent call last):
  File "/home/meet/venv/bk-planner/lib/python3.10/site-packages/ninja_extra/operation.py", line 195, in run
    _processed_results = self._result_to_response(
  File "/home/meet/venv/bk-planner/lib/python3.10/site-packages/ninja/operation.py", line 260, in _result_to_response
    validated_object = response_model.model_validate(
  File "/home/meet/venv/bk-planner/lib/python3.10/site-packages/pydantic/main.py", line 568, in model_validate
    return cls.__pydantic_validator__.validate_python(
pydantic_core._pydantic_core.ValidationError: 4 validation errors for NinjaResponseSchema
response.results.0.id
  Field required [type=missing, input_value=<DjangoGetter: <HTTPStatu...RNAL_SERVER_ERROR: 500>>, input_type=DjangoGetter]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
response.results.0.username
  Field required [type=missing, input_value=<DjangoGetter: <HTTPStatu...RNAL_SERVER_ERROR: 500>>, input_type=DjangoGetter]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
response.results.1.id
  Field required [type=missing, input_value=<DjangoGetter: ErrorSchem...try later.', code=None)>, input_type=DjangoGetter]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
response.results.1.username
  Field required [type=missing, input_value=<DjangoGetter: ErrorSchem...try later.', code=None)>, input_type=DjangoGetter]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
```
